name: CI Calculadora Promedio

on:
  push:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Validar código (ESLint)
        run: npx eslint .

      - name: Ejecutar pruebas
        run: npm test

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            set -e
            docker stop mi-app || true
            docker rm mi-app || true
            rm -rf proyecto-evaluacion
            git clone https://github.com/BenRice-K/Cal-devops.git proyecto-evaluacion
            cd proyecto-evaluacion
            docker build -t imagen-mi-app .
            docker run -d -p 80:3000 --name mi-app imagen-mi-app

